import {chromium} from '@playwright/test';
import {createServer} from 'node:http';import {readFile,mkdir} from 'node:fs/promises';import assert from 'node:assert/strict';import gifenc from 'gifenc';import gifuct from 'gifuct-js';const {GIFEncoder}=gifenc;const {parseGIF}=gifuct;
const state={device:'test-device',uptime:1842,heap:123456,sd:true,storageTotal:32*1073741824,storageUsed:6*1073741824,connected:true,ssid:'Home studio',ip:'192.168.1.50',apIP:'192.168.4.1',rssi:-48,width:320,height:240,title:'A quiet afternoon',current:63,duration:204,playing:false,slotSize:5242880,firmware:'test build',settings:{volume:65,volumeStep:5,voice:0,autoNext:1,shuffle:0,wifi:1,admin:1,colors:[[160,3,98],[155,9,94],[205,30,22],[160,30,79],[205,17,49],[165,19,88]]},ai:{provider:'backend'}};
const requests=[],actions=[];let uploads=0;
const server=createServer(async(req,res)=>{try{requests.push(req.url);if(req.url.startsWith('/api/')){let body='';for await(const chunk of req)body+=chunk;const params=new URLSearchParams(body);if(req.method==='POST')actions.push({url:req.url,body:Object.fromEntries(params)});let data={ok:true};if(req.url==='/api/session')data=req.method==='POST'?{token:'test-token'}:{setup:false};else if(req.url==='/api/status')data=state;else if(req.url.startsWith('/api/files'))data={files:[{name:'Morning garden.jpg',size:48123},{name:'Summer.gif',size:294820}]};else if(req.url==='/api/settings'){Object.assign(state.settings,JSON.parse(params.get('values')));state.settingsResult='Settings saved';}else if(req.url.startsWith('/api/upload'))uploads++;else if(req.url==='/api/ota')data={state:'idle'};res.setHeader('Content-Type','application/json');res.end(JSON.stringify(data));return;}const path=req.url==='/'?'index.html':req.url.slice(1);const bytes=await readFile(new URL('../dist/'+path,import.meta.url));res.setHeader('Content-Type',path.endsWith('.js')?'text/javascript':path.endsWith('.css')?'text/css':'text/html');res.end(bytes);}catch{res.writeHead(404);res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[],external=[];page.on('dialog',async d=>{errors.push('Unexpected native dialog: '+d.type());await d.dismiss();});page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(origin)&&!r.url().startsWith('blob:')&&!r.url().startsWith('data:'))external.push(r.url());});
try{
 await page.goto(origin);await page.locator('[name=username]').fill('owner');await page.locator('#loginForm [name=password]').fill('test-password');await page.locator('#loginForm button').click();await page.locator('#dashboard').waitFor();assert.equal(await page.locator('.widget').count(),6);
 await page.getByRole('button',{name:'ลบ เครือข่าย',exact:true}).click();assert.equal(await page.locator('.widget').count(),5);await page.reload();await page.locator('#dashboard').waitFor();assert.equal(await page.locator('.widget').count(),5);await page.locator('#addType').selectOption('network',{force:true});await page.locator('#addBlock').click();assert.equal(await page.locator('.widget').count(),6);
 const handle=page.locator('.resize').first();await handle.focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('.widget').first().evaluate(e=>e.style.getPropertyValue('--span')),'9');await page.keyboard.press('ArrowDown');assert.equal(await page.locator('.widget').first().evaluate(e=>e.getBoundingClientRect().height),300);await page.locator('.resize').nth(1).focus();await page.keyboard.press('ArrowDown');assert.equal(await page.locator('.widget').nth(1).evaluate(e=>e.getBoundingClientRect().height),300);assert.ok(await page.getByRole('progressbar').count()>=4);
 const grip=await page.locator('.resize').first().boundingBox();await page.mouse.move(grip.x+5,grip.y+5);await page.mouse.down();await page.mouse.move(grip.x+15,grip.y+25);await page.mouse.up();assert.equal(await page.locator('.widget').first().evaluate(e=>e.getBoundingClientRect().height),300);

 await page.locator('.sparkline').waitFor();assert.ok(await page.locator('.sparkline polyline').getAttribute('points'));await mkdir('../docs/build/web-preview',{recursive:true});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'../docs/build/web-preview/dashboard.png',fullPage:true});
 await page.locator('nav a[href="#settings"]').click();await page.locator('[name=voice]').check();await page.locator('#soundSettings button.primary').click();await page.waitForTimeout(100);assert.equal(state.settings.voice,1);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'../docs/build/web-preview/settings.png',fullPage:true});
 await page.locator('nav a[href="#wifi"]').click();await page.locator('[name=ssid]').fill('New network');await page.locator('#wifiForm button').click();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'../docs/build/web-preview/wifi.png',fullPage:true});
 await page.locator('nav a[href="#files"]').click();
 await page.locator('#directory + .select-control').click();await page.getByRole('option',{name:'เพลง',exact:true}).click();assert.equal(await page.locator('#directory').inputValue(),'Musics');await page.locator('#directory + .select-control').click();await page.keyboard.press('Home');await page.keyboard.press('Enter');assert.equal(await page.locator('#directory').inputValue(),'Pictures');
 await page.locator('[data-op=rename]').first().click();await page.locator('.action-modal').waitFor();await page.locator('.action-modal input').fill('renamed.jpg');await page.locator('.action-modal button.primary').click();await page.waitForTimeout(100);assert.equal(actions.at(-1).body.newName,'renamed.jpg');
 const beforeDelete=actions.length;await page.locator('[data-op=delete]').first().click();await page.screenshot({path:'../docs/build/web-preview/confirm-modal.png'});await page.keyboard.press('Escape');assert.equal(actions.length,beforeDelete);await page.locator('[data-op=delete]').first().click();await page.locator('.action-modal button.primary').click();await page.waitForTimeout(100);assert.equal(actions.at(-1).body.action,'delete');
 const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=640;c.height=480;const x=c.getContext('2d');x.fillStyle='#dfba9d';x.fillRect(0,0,640,480);x.fillStyle='#7c9b83';x.fillRect(80,80,400,240);return c.toDataURL().split(',')[1];});await page.locator('#mediaInput').setInputFiles({name:'landscape.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await page.locator('#editor').waitFor({state:'visible'});await page.locator('#process').click();await page.waitForFunction(()=>!document.querySelector('#uploadPrepared').disabled);assert.equal(uploads,0);const shape=await page.locator('#prepared img').evaluate(async e=>{await e.decode();return[e.naturalWidth,e.naturalHeight];});assert.deepEqual(shape,[320,240]);await page.locator('#uploadPrepared').click();await page.waitForTimeout(100);assert.equal(uploads,1);
 await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'../docs/build/web-preview/media.png',fullPage:true});
 const gif=GIFEncoder();for(let i=0;i<2;i++)gif.writeFrame(new Uint8Array(16*16).fill(i),16,16,{palette:[[255,0,0],[0,255,0]],delay:100,repeat:0});gif.finish();await page.locator('#mediaInput').setInputFiles({name:'animation.gif',mimeType:'image/gif',buffer:Buffer.from(gif.bytes())});await page.waitForFunction(()=>document.querySelector('#format').value==='gif');await page.locator('#process').click();await page.waitForFunction(()=>!document.querySelector('#uploadPrepared').disabled);assert.match(await page.locator('#uploadName').inputValue(),/\.gif$/);assert.equal(uploads,1);
 const gifBytes=await page.locator('#prepared img').evaluate(async img=>[...new Uint8Array(await(await fetch(img.src)).arrayBuffer())]);const decoded=parseGIF(Uint8Array.from(gifBytes).buffer);assert.equal(decoded.frames.filter(f=>f.image).length,2);assert.equal(decoded.lsd.width,320);assert.equal(decoded.lsd.height,240);
 await page.locator('#format').selectOption('png',{force:true});await page.locator('#process').click();await page.waitForFunction(()=>!document.querySelector('#uploadPrepared').disabled);assert.match(await page.locator('#uploadName').inputValue(),/\.png$/);assert.equal(uploads,1);
 await page.locator('#outW').fill('0');await page.locator('#process').click();await page.waitForFunction(()=>document.querySelector('#notice').classList.contains('error'));assert.equal(await page.locator('#uploadPrepared').isDisabled(),true);await page.locator('#outW').fill('320');
 await page.locator('nav a[href="#ota"]').click();await page.locator('#otaUrl [name=url]').fill('https://example.test/firmware.bin');const beforeOTA=actions.length;await page.locator('#otaUrl button').click();await page.locator('.action-modal').waitFor();await page.keyboard.press('Escape');assert.equal(actions.length,beforeOTA);assert.equal(await page.locator('.file-pick-button').count(),1);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'../docs/build/web-preview/ota.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.locator('nav a[href="#dashboard"]').click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'../docs/build/web-preview/mobile.png',fullPage:true});await page.locator('nav a[href="#files"]').click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);assert.deepEqual(external,[]);console.log('Browser: login, persisted widgets, keyboard resize, settings, WiFi, local PNG/JPEG and animated GIF, upload, OTA page, mobile layout passed; no external requests.');
}finally{await browser.close();server.close();}
