#include "DisplayManager.hpp"
#include "FileManager.hpp"
#define DISPLAYMANAGER_HH

TFT_eSPI tft = TFT_eSPI();
TFT_eSprite txtDis = TFT_eSprite(&tft);
DisplayManager DISM;

const char *giphy = "/main/Pictures/giphy2.gif";
const char *fan = "/main/Pictures/fan.gif";
const char *robot = "/main/Pictures/robot240.gif";
const char *mp3File = "/main/Musics/Exil_-_Hiboky.mp3";

static int xOffset = 0;
static int yOffset = 0;

int offsetY_of_scroll = 0;
bool isDisplay_install;

DisplayManager::DisplayManager() {
    
}

DisplayManager::~DisplayManager() {
    
}

void DisplayManager::autoScroll() {
    
}

void DisplayManager::initDisplay(){
    if(xSemaphoreTake(displaySemaphore, pdMS_TO_TICKS(500)) == pdTRUE) {
        tft.init();
        tft.setRotation(0);
        tft.setTextSize(2);
        tft.fillScreen(TFT_BLACK);
        isDisplay_install = true;
        xSemaphoreGive(displaySemaphore);
    }
}

void DisplayManager::resetDisplay(){
    if (xSemaphoreTake(displaySemaphore, pdMS_TO_TICKS(100)) == pdTRUE) {
        tft.fillScreen(TFT_BLACK);
        tft.setCursor(0, 0);
        xSemaphoreGive(displaySemaphore);
    }
}

void println(String &text) {
    tft.println(text.c_str());
}

void println(const String &text) {
    tft.println(text.c_str());
}

void println(char &text) {
    tft.println(text);
}

void println(const char &text) {
    tft.println(text);
}

void println(int &text) {
    tft.println(text);
}

void println(const int &text) {
    tft.println(text);
}

void println(long &text) {
    tft.println(text);
}

void println(const long &text) {
    tft.println(text);
}

void println(float &text) {
    tft.println(text);
}

void println(const float &text) {
    tft.println(text);
}

void println(double &text) {
    tft.println(text);
}

void println(const double &text) {
    tft.println(text);
}

void DisplayManager::createArray(const char *filename) {
    File jpgFile = SD.open(filename, FILE_READ);

    if (!jpgFile) {
        Serial.print("ERROR: File \""); Serial.print(filename); Serial.println ("\" not found!");
        return;
    }

    uint8_t data;
    byte line_len = 0;
    Serial.println("");
    Serial.println("// Generated by a JPEGDecoder library example sketch:");
    Serial.println("// https://github.com/Bodmer/JPEGDecoder");
    Serial.println("");
    Serial.println("#if defined(__AVR__)");
    Serial.println("  #include <avr/pgmspace.h>");
    Serial.println("#endif");
    Serial.println("");
    Serial.print  ("const uint8_t ");
    while (*filename != '.') Serial.print(*filename++);
    Serial.println("[] PROGMEM = {");

    while (jpgFile.available()) {
        data = jpgFile.read();
        Serial.print("0x"); if (abs(data) < 16) Serial.print("0");
        Serial.print(data, HEX); Serial.print(",");
        line_len++;
        if (line_len >= 32) {
            line_len = 0;
            Serial.println();
        }
    }

    Serial.println("};\r\n");
    jpgFile.close();
}

void DisplayManager::jpegInfo() {
    Serial.println("===============");
    Serial.println("JPEG image info");
    Serial.println("===============");
    Serial.print  ("Width      :"); Serial.println(JpegDec.width);
    Serial.print  ("Height     :"); Serial.println(JpegDec.height);
    Serial.print  ("Components :"); Serial.println(JpegDec.comps);
    Serial.print  ("MCU / row  :"); Serial.println(JpegDec.MCUSPerRow);
    Serial.print  ("MCU / col  :"); Serial.println(JpegDec.MCUSPerCol);
    Serial.print  ("Scan type  :"); Serial.println(JpegDec.scanType);
    Serial.print  ("MCU width  :"); Serial.println(JpegDec.MCUWidth);
    Serial.print  ("MCU height :"); Serial.println(JpegDec.MCUHeight);
    Serial.println("===============");
    Serial.println("");
}

void DisplayManager::jpegRender(int xpos, int ypos) {
    uint16_t  *pImg;
    uint16_t mcu_w = JpegDec.MCUWidth;
    uint16_t mcu_h = JpegDec.MCUHeight;
    uint32_t max_x = JpegDec.width;
    uint32_t max_y = JpegDec.height;

    uint32_t min_w = minimum(mcu_w, max_x % mcu_w);
    uint32_t min_h = minimum(mcu_h, max_y % mcu_h);

    uint32_t win_w = mcu_w;
    uint32_t win_h = mcu_h;

    uint32_t drawTime = millis();

    max_x += xpos;
    max_y += ypos;

  // read each MCU block until there are no more
#ifdef USE_SPI_BUFFER
    while (JpegDec.readSwappedBytes()) {
#else
    while (JpegDec.read()) {
#endif
        pImg = JpegDec.pImage;

        int mcu_x = JpegDec.MCUx * mcu_w + xpos;
        int mcu_y = JpegDec.MCUy * mcu_h + ypos;

        if (mcu_y < tft.height()) {
            if (mcu_x + mcu_w <= max_x) win_w = mcu_w;
            else win_w = min_w;

            if (mcu_y + mcu_h <= max_y) win_h = mcu_h;
            else win_h = min_h;

            if (win_w != mcu_w) {
                for (int h = 1; h < win_h; h++) {
                    memcpy(pImg + h * win_w, pImg + h * mcu_w, win_w << 1);
                }
            }
            if(xSemaphoreTake(displaySemaphore, pdMS_TO_TICKS(100)) == pdTRUE) {
                tft.pushImage(mcu_x, mcu_y, win_w, win_h, pImg);
                xSemaphoreGive(displaySemaphore);
            }
        } else {
            JpegDec.abort();
        }
    }

    drawTime = millis() - drawTime;
    Serial.print("Total render time was    : "); Serial.print(drawTime); Serial.println(" ms");
    Serial.println("=====================================");
}

void DisplayManager::drawJpeg(const char *filename, int xpos, int ypos) {
    Serial.println("===========================");
    Serial.print("Drawing file: "); Serial.println(filename);
    Serial.println("===========================");

    if(xSemaphoreTake(sdSemaphore, pdMS_TO_TICKS(100)) == pdTRUE) {
        File jpegFile = SD.open(filename, FILE_READ);

        if (!jpegFile) {
            Serial.println("open file error.");
            xSemaphoreGive(sdSemaphore);
            return;
        }

        boolean decoded = JpegDec.decodeSdFile(jpegFile);
        if (decoded) {
            jpegRender(xpos, ypos);
        } else {
            Serial.println("Jpeg file format not supported!");
        }
        xSemaphoreGive(sdSemaphore);
    }
}

void handleDisplay(void *pvParameters) {
    DISPLAY_COMMAND cmd;
    enum class STATE { IDLE, SHOW, CLEAR } state = STATE::IDLE;
    String lastPath = "";

    for (;;) {
        if(xQueueReceive(display_command, &cmd, 10) == pdPASS) {
            if(cmd.module == DISPLAY_COMMAND::MODULE::DIS) {
                
                if(cmd.display_state == DISPLAY_COMMAND::DISPLAY_STATE::SHOW) {
                    lastPath = cmd.path;
                    state = STATE::SHOW;
                    Serial.println("SHOW OK. Path: " + lastPath);
                }

                if(cmd.display_state == DISPLAY_COMMAND::DISPLAY_STATE::CLEAR) {
                    state = STATE::CLEAR;
                    Serial.println("CLEAR OK.");
                }
            }
        }

        switch (state) {
        case STATE::SHOW:
            if (lastPath != "") {
                String pathLower = lastPath;
                DISM.resetDisplay();
                
                if (pathLower.endsWith(".jpg") || pathLower.endsWith(".jpeg")) {
                    DISM.drawJpeg(lastPath.c_str(), 0, 40);
                }
            }
            
            state = STATE::IDLE;
            vTaskDelay(pdMS_TO_TICKS(10));
            break;

        case STATE::CLEAR:
            DISM.resetDisplay(); 
            state = STATE::IDLE;
            vTaskDelay(pdMS_TO_TICKS(10));
            break;
        
        default:
            vTaskDelay(pdMS_TO_TICKS(50));
            break;
        } 
    }

    vTaskDelay(pdMS_TO_TICKS(1));
}