#include "DisplayManager.hpp"
#include "FileManager.hpp"
#define DISPLAYMANAGER_HH

TFT_eSPI tft = TFT_eSPI();
DisplayManager DISM;

AnimatedGIF gif;
File gifFile;
bool isGifPlaying = false;

static int iXOff = 0; 
static int iYOff = 0;

bool isDisplay_install;

DisplayManager::DisplayManager() {
    
}

DisplayManager::~DisplayManager() {
    
}

void DisplayManager::initDisplay(){
    if(xSemaphoreTake(displaySemaphore, pdMS_TO_TICKS(500)) == pdTRUE) {
        tft.init();
        tft.setRotation(1  );
        tft.setTextSize(2);
        tft.fillScreen(TFT_BLACK);

        isDisplay_install = true;
        xSemaphoreGive(displaySemaphore);
    }
}

void DisplayManager::resetDisplay(){
    if (xSemaphoreTake(displaySemaphore, pdMS_TO_TICKS(100)) == pdTRUE) {
        tft.fillScreen(TFT_BLACK);
        tft.setCursor(0, 0);
        xSemaphoreGive(displaySemaphore);
    }
}

void DisplayManager::createArray(const char *filename) {
    File jpgFile = SD.open(filename, FILE_READ);

    if (!jpgFile) {
        Serial.print("ERROR: File \""); Serial.print(filename); Serial.println ("\" not found!");
        return;
    }

    uint8_t data;
    byte line_len = 0;
    Serial.println("");
    Serial.println("// Generated by a JPEGDecoder library example sketch:");
    Serial.println("// https://github.com/Bodmer/JPEGDecoder");
    Serial.println("");
    Serial.println("#if defined(__AVR__)");
    Serial.println("  #include <avr/pgmspace.h>");
    Serial.println("#endif");
    Serial.println("");
    Serial.print  ("const uint8_t ");
    while (*filename != '.') Serial.print(*filename++);
    Serial.println("[] PROGMEM = {");

    while (jpgFile.available()) {
        data = jpgFile.read();
        Serial.print("0x"); if (abs(data) < 16) Serial.print("0");
        Serial.print(data, HEX); Serial.print(",");
        line_len++;
        if (line_len >= 32) {
            line_len = 0;
            Serial.println();
        }
    }

    Serial.println("};\r\n");
    jpgFile.close();
}

void DisplayManager::jpegInfo() {
    Serial.println("===============");
    Serial.println("JPEG image info");
    Serial.println("===============");
    Serial.print  ("Width      :"); Serial.println(JpegDec.width);
    Serial.print  ("Height     :"); Serial.println(JpegDec.height);
    Serial.print  ("Components :"); Serial.println(JpegDec.comps);
    Serial.print  ("MCU / row  :"); Serial.println(JpegDec.MCUSPerRow);
    Serial.print  ("MCU / col  :"); Serial.println(JpegDec.MCUSPerCol);
    Serial.print  ("Scan type  :"); Serial.println(JpegDec.scanType);
    Serial.print  ("MCU width  :"); Serial.println(JpegDec.MCUWidth);
    Serial.print  ("MCU height :"); Serial.println(JpegDec.MCUHeight);
    Serial.println("===============");
    Serial.println("");
}

void DisplayManager::jpegRender(int xpos, int ypos) {
    uint16_t  *pImg;
    uint16_t mcu_w = JpegDec.MCUWidth;
    uint16_t mcu_h = JpegDec.MCUHeight;
    uint32_t max_x = JpegDec.width;
    uint32_t max_y = JpegDec.height;

    uint32_t min_w = minimum(mcu_w, max_x % mcu_w);
    uint32_t min_h = minimum(mcu_h, max_y % mcu_h);

    uint32_t win_w = mcu_w;
    uint32_t win_h = mcu_h;

    uint32_t drawTime = millis();

    max_x += xpos;
    max_y += ypos;

  // read each MCU block until there are no more
#ifdef USE_SPI_BUFFER
    while (JpegDec.readSwappedBytes()) {
#else
    while (JpegDec.read()) {
#endif
        pImg = JpegDec.pImage;

        int mcu_x = JpegDec.MCUx * mcu_w + xpos;
        int mcu_y = JpegDec.MCUy * mcu_h + ypos;

        if (mcu_y < tft.height()) {
            if (mcu_x + mcu_w <= max_x) win_w = mcu_w;
            else win_w = min_w;

            if (mcu_y + mcu_h <= max_y) win_h = mcu_h;
            else win_h = min_h;

            if (win_w != mcu_w) {
                for (int h = 1; h < win_h; h++) {
                    memcpy(pImg + h * win_w, pImg + h * mcu_w, win_w << 1);
                }
            }
            if(xSemaphoreTake(displaySemaphore, pdMS_TO_TICKS(100)) == pdTRUE) {
                tft.pushImage(mcu_x, mcu_y, win_w, win_h, pImg);
                xSemaphoreGive(displaySemaphore);
            }
        } else {
            JpegDec.abort();
        }
    }

    drawTime = millis() - drawTime;
    Serial.print("Total render time was    : "); Serial.print(drawTime); Serial.println(" ms");
    Serial.println("=====================================");
}

void DisplayManager::drawJpeg(const char *filename, int xpos, int ypos) {
    Serial.println("===========================");
    Serial.print("Drawing file: "); Serial.println(filename);
    Serial.println("===========================");

    if(xSemaphoreTake(sdSemaphore, pdMS_TO_TICKS(100)) == pdTRUE) {
        File jpegFile = SD.open(filename, FILE_READ);

        if (!jpegFile) {
            Serial.println("open file error.");
            xSemaphoreGive(sdSemaphore);
            return;
        }

        boolean decoded = JpegDec.decodeSdFile(jpegFile);
        if (decoded) {
            jpegRender(xpos, ypos);
        } else {
            Serial.println("Jpeg file format not supported!");
        }
        xSemaphoreGive(sdSemaphore);
    }
}

// ==========================================
// Callback Functions สำหรับ AnimatedGIF
// ==========================================
void * GIFOpenFile(const char *fname, int32_t *pSize) {
  if(xSemaphoreTake(sdSemaphore, portMAX_DELAY) == pdTRUE) {
      gifFile = SD.open(fname);
      if (gifFile) {
        *pSize = gifFile.size();
        xSemaphoreGive(sdSemaphore);
        return (void *)&gifFile;
      }
      xSemaphoreGive(sdSemaphore);
  }
  return NULL;
}

void GIFCloseFile(void *pHandle) { 
  if(xSemaphoreTake(sdSemaphore, portMAX_DELAY) == pdTRUE) {
      gifFile.close(); 
      xSemaphoreGive(sdSemaphore);
  }
}

int32_t GIFReadFile(GIFFILE *pFile, uint8_t *pBuf, int32_t iLen) { 
    int32_t bytesRead = 0;
    if(xSemaphoreTake(sdSemaphore, portMAX_DELAY) == pdTRUE) {
        // 🌟 ให้ ESP32 จัดการเรื่อง EOF เองล้วนๆ ไม่ต้องมี Work-around
        bytesRead = gifFile.read(pBuf, iLen);
        pFile->iPos = gifFile.position();
        xSemaphoreGive(sdSemaphore);
    }
    return bytesRead;
}

int32_t GIFSeekFile(GIFFILE *pFile, int32_t iPosition) { 
    if(xSemaphoreTake(sdSemaphore, portMAX_DELAY) == pdTRUE) {
        gifFile.seek(iPosition);
        pFile->iPos = gifFile.position();
        xSemaphoreGive(sdSemaphore);
    }
    return pFile->iPos;
}

#define BUFFER_SIZE 256
uint16_t usTemp[1][BUFFER_SIZE]; 

void GIFDraw(GIFDRAW *pDraw) {
  uint8_t *s;
  uint16_t *d, *usPalette;
  int x, y, iWidth, iCount;

  iWidth = pDraw->iWidth;
  if (iWidth + pDraw->iX > tft.width()) iWidth = tft.width() - pDraw->iX;
    
  usPalette = pDraw->pPalette;
  y = iYOff + pDraw->iY + pDraw->y; // จัดกึ่งกลางแนวตั้ง

  if (y >= tft.height() || (iXOff + pDraw->iX) >= tft.width() || iWidth < 1) return;

  s = pDraw->pPixels;
  if (pDraw->ucDisposalMethod == 2) { 
    for (x = 0; x < iWidth; x++) {
      if (s[x] == pDraw->ucTransparent) s[x] = pDraw->ucBackground;
    }
    pDraw->ucHasTransparency = 0;
  }

  // 🌟 รอคิวหน้าจอ
  if (xSemaphoreTake(displaySemaphore, portMAX_DELAY) == pdTRUE) {
      if (pDraw->y == 0) Serial.println(">>> DRAWING 1 FRAME! <<<");
      // --- กรณีที่ 1: ภาพมีพื้นหลังโปร่งใส ---
      if (pDraw->ucHasTransparency) {
        uint8_t *pEnd, c, ucTransparent = pDraw->ucTransparent;
        pEnd = s + iWidth;
        x = 0;
        iCount = 0;
        
        while (x < iWidth) {
          c = ucTransparent - 1;
          d = &usTemp[0][0];
          
          while (c != ucTransparent && s < pEnd && iCount < BUFFER_SIZE) {
            c = *s++;
            if (c == ucTransparent) s--; 
            else { *d++ = usPalette[c]; iCount++; }
          } 
          
          if (iCount) {
            // 🌟 เปลี่ยนมาใช้ pushImage แก้ปัญหาหน้าจอไม่รับข้อมูล
            tft.pushImage(iXOff + pDraw->iX + x, y, iCount, 1, usTemp[0]);
            x += iCount;
            iCount = 0;
          }
          
          c = ucTransparent;
          while (c == ucTransparent && s < pEnd) {
            c = *s++;
            if (c == ucTransparent) x++; else s--;
          }
        }
      } 
      // --- กรณีที่ 2: ภาพทึบปกติ (เขียนโค้ดให้สั้นและไวขึ้นมาก) ---
      else {
        s = pDraw->pPixels;
        int currentX = iXOff + pDraw->iX; 
        
        while (iWidth > 0) {
            int toDraw = (iWidth <= BUFFER_SIZE) ? iWidth : BUFFER_SIZE;
            for (iCount = 0; iCount < toDraw; iCount++) {
                usTemp[0][iCount] = usPalette[*s++];
            }
            // 🌟 เปลี่ยนมาใช้ pushImage
            tft.pushImage(currentX, y, toDraw, 1, usTemp[0]);
            currentX += toDraw;
            iWidth -= toDraw;
        }
      }
      xSemaphoreGive(displaySemaphore);
  }
}

// ==========================================

bool DisplayManager::openGif(const char *filename) {
    gif.begin(GIF_PALETTE_RGB565_BE);
    if (gif.open(filename, GIFOpenFile, GIFCloseFile, GIFReadFile, GIFSeekFile, GIFDraw)) {
        Serial.printf("Playing GIF: %s\n", filename);
        
        // 🌟 คำนวณจัดกึ่งกลางภาพ
        iXOff = (tft.width() - gif.getCanvasWidth()) / 2;
        if (iXOff < 0) iXOff = 0;
        
        iYOff = (tft.height() - gif.getCanvasHeight()) / 2;
        if (iYOff < 0) iYOff = 0;
        
        return true;
    } else {
        Serial.println("Failed to open GIF file.");
        return false;
    }
}

int DisplayManager::playGifFrame() {
    // คืนค่ากลับไปให้ handleDisplay รู้ว่าเล่นจบหรือ Error หรือยัง
    return gif.playFrame(true, NULL); 
}

void DisplayManager::stopGif() {
    gif.close();
    Serial.println("GIF Stopped.");
}

// 🌟 นำโค้ด Task ตัวที่ถูกต้องมาใช้งาน (เช็ค waitTime)
void handleDisplay(void *pvParameters) {
    DISPLAY_COMMAND cmd;
    enum class STATE { IDLE, SHOW, CLEAR, PLAYING_GIF } state = STATE::IDLE;
    String lastPath = "";

    for (;;) {
        // 🌟 ไม่ Block คิวเวลาเล่น GIF ทำให้เฟรมเรตไม่ตก
        TickType_t waitTime = (state == STATE::PLAYING_GIF) ? pdMS_TO_TICKS(5) : pdMS_TO_TICKS(10);
        
        if(xQueueReceive(display_command, &cmd, waitTime) == pdPASS) {
            if(cmd.module == DISPLAY_COMMAND::MODULE::DIS) {
                
                if(cmd.display_state == DISPLAY_COMMAND::DISPLAY_STATE::SHOW) {
                    lastPath = cmd.path;
                    if(state == STATE::PLAYING_GIF) DISM.stopGif();
                    state = STATE::SHOW;
                    Serial.println("SHOW OK. Path: " + lastPath);
                }

                if(cmd.display_state == DISPLAY_COMMAND::DISPLAY_STATE::CLEAR) {
                    if(state == STATE::PLAYING_GIF) DISM.stopGif();
                    state = STATE::CLEAR;
                    Serial.println("CLEAR OK.");
                }
            }
        }

        switch (state) {
        case STATE::SHOW:
            if (lastPath != "") {
                String pathLower = lastPath;
                pathLower.toLowerCase();
                DISM.resetDisplay();
                
                if (pathLower.endsWith(".jpg") || pathLower.endsWith(".jpeg")) {
                    DISM.drawJpeg(lastPath.c_str(), 0, 40);
                    state = STATE::IDLE; 
                } else if(pathLower.endsWith(".gif")){
                    if(DISM.openGif(lastPath.c_str())) {
                        Serial.println("openedd.");
                        state = STATE::PLAYING_GIF; 
                    } else {
                        state = STATE::IDLE;
                    }
                } else {
                     state = STATE::IDLE;
                }
            } else {
                state = STATE::IDLE;
            }
            break;

        case STATE::PLAYING_GIF:
        {   // 🌟 ใส่ปีกกาครอบเคสนี้ไว้ด้วย
            int result = DISM.playGifFrame();
            
            // ถ้าเล่นจนจบไฟล์แล้ว (<= 0)
            if (result <= 0) {
                DISM.stopGif(); // ปิดไฟล์เก่า
                
                // 🌟 พยายามเปิดไฟล์เดิมอีกครั้ง เพื่อเล่นแบบวนลูป
                if (DISM.openGif(lastPath.c_str())) {
                    // เปิดสำเร็จ จะทำงานต่อในลูปหน้า
                } else {
                    // แต่ถ้าไฟล์พัง เปิดไม่ติด ให้กลับไปหน้าจอดำ (IDLE) เพื่อไม่ให้สแปม
                    state = STATE::IDLE;
                }
            }
            vTaskDelay(pdMS_TO_TICKS(1)); 
            break;
        }

        case STATE::CLEAR:
            DISM.resetDisplay();
            state = STATE::IDLE;
            vTaskDelay(pdMS_TO_TICKS(10));
            break;
        
        case STATE::IDLE:
        default:
            vTaskDelay(pdMS_TO_TICKS(50));
            break;
        } 
    }
}