import {cropControls} from './crop-controls.mjs';
import {mjpegFrames} from './mjpeg.mjs';
import {startIcons} from './icons.mjs';
import {sizeCard,observeCards} from './card-sizing.mjs';
import {mobileMenu} from './mobile-menu.mjs';
import {ask,requestName,enhanceControls} from './components.mjs';
import {widgetContent,recordStatus} from './dashboard.mjs';
import {widgets,defaults,layout,rect,dimensions,bytes,time,snapWidth,snapHeight,playableAudio,mediaDirectory,directAudioNameFromUrl,blockedYouTubeUrl} from './model.mjs';
const $=(s,root=document)=>root.querySelector(s),$$=(s,root=document)=>[...root.querySelectorAll(s)];
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const MiB=1048576,softUploadBytes=256*MiB,uploadReserveBytes=64*1024;
function storageFree(){const total=Number(status.storageTotal),used=Number(status.storageUsed);return Number.isFinite(total)&&Number.isFinite(used)&&total>=used?total-used:null;}
const pages={dashboard:['ภาพรวม','พื้นที่ของคุณ จัดวางในแบบที่ชอบ'],files:['ไฟล์และมีเดีย','เตรียมภาพให้พอดีกับจอ ทุกขั้นตอนอยู่ในเบราว์เซอร์ของคุณ'],wifi:['WiFi Manager','เชื่อมต่อและจัดการเครือข่ายของอุปกรณ์'],settings:['การตั้งค่า','สี เสียง และการทำงานที่เป็นคุณ'],ai:['AI conversation','ตั้งค่าบริการสนทนาที่อุปกรณ์ใช้งาน'],ota:['อัปเดตเฟิร์มแวร์','อัปเดตจากไฟล์หรือลิงก์โดยตรง'],account:['บัญชี','จัดการการเข้าถึงอุปกรณ์']};
let token=sessionStorage.getItem('tofan-session')||'',status={},blocks=defaults(),page='',polling=false,worker=null,original=null,processed=null,previewURL='',previewImage=null,xhr=null,videoProcessing=false,videoProcessCancelled=false;
let stopCardObserver=null,cropUI=null,lastAudioImportState='';
let panX=0,panY=0,blockKey='tofan-layout',layoutLoaded=false;
function notice(text,error=false){const n=$('#notice');n.hidden=!text;n.replaceChildren();n.className=error?'error':'';if(!text)return;const message=document.createElement('span');message.textContent=text;const close=document.createElement('button');close.type='button';close.textContent='×';close.setAttribute('aria-label','ปิดการแจ้งเตือน');close.onclick=()=>n.hidden=true;n.append(message,close);}

async function api(path,data){const response=await fetch('/api/'+path,{method:data?'POST':'GET',headers:{Authorization:`Bearer ${token}`,'X-ToFan-Client':'portal',...(data?{'Content-Type':'application/x-www-form-urlencoded'}:{})},body:data?new URLSearchParams(data):undefined});const json=await response.json();if(!response.ok){if(response.status===401&&path!=='session')signout();throw Error(json.error||`HTTP ${response.status}`);}return json;}
function attempt(fn){return async e=>{e?.preventDefault();try{await fn(e);}catch(error){notice(error.message,true);}};}
function signout(){token='';sessionStorage.removeItem('tofan-session');$('#shell').hidden=true;$('#login').hidden=false;}
async function boot(){const info=await api('session');$('#loginTitle').textContent=info.setup?'เริ่มต้นพื้นที่ของคุณ':'ยินดีต้อนรับกลับ';$('#loginHelp').textContent=info.setup?'เชื่อมต่อ WiFi ของ ToFan แล้วสร้างบัญชีผู้ดูแลครั้งแรก':'เข้าสู่ระบบเพื่อจัดการ ToFan';$('#loginForm [name=password]').minLength=info.setup?8:1;$('#loginForm button').textContent=info.setup?'สร้างบัญชีและเริ่มใช้งาน':'เข้าสู่ระบบ';if(token)await open();}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const button=$('button',e.target);button.disabled=true;try{const d=await api('session',Object.fromEntries(new FormData(e.target)));token=d.token;sessionStorage.setItem('tofan-session',token);await open();}catch(err){notice(err.message,true);}finally{button.disabled=false;}};
$('#logout').onclick=attempt(async()=>{await api('logout',{});signout();});
async function open(){status=await api('status');recordStatus(status);$('#login').hidden=true;$('#shell').hidden=false;layoutLoaded=false;loadLayout();applyWebTheme();render();}
function loadLayout(){if(layoutLoaded||!status.device)return;blockKey='tofan-layout-'+status.device;try{blocks=layout(JSON.parse(localStorage.getItem(blockKey))??defaults());}catch{blocks=defaults();}layoutLoaded=true;}
function applyWebTheme(){
 const names=['--bg','--surface','--text','--accent','--muted','--selection'];
 status.settings?.colors?.forEach(([h,s,v],i)=>{s/=100;v/=100;const f=n=>{const k=(n+h/60)%6;return Math.round(255*(v-v*s*Math.max(0,Math.min(k,4-k,1))));};const rgb=[f(5),f(3),f(1)];document.documentElement.style.setProperty(names[i],`rgb(${rgb.join(',')})`);if(i===3)document.documentElement.style.setProperty('--button-text',(rgb[0]*299+rgb[1]*587+rgb[2]*114)>145000?'#243b31':'#ffffff');});
}
function saveLayout(){try{localStorage.setItem(blockKey,JSON.stringify(blocks));}catch{notice('เบราว์เซอร์ไม่อนุญาตให้จดจำ layout',true);}}
function render(){if(!token)return;stopCardObserver?.();stopCardObserver=null;videoProcessCancelled=true;if(worker){worker.terminate();worker=null;}if(previewURL){URL.revokeObjectURL(previewURL);previewURL='';}previewImage?.close?.();original=processed=previewImage=null;page=location.hash.slice(1);if(!pages[page])page='dashboard';$('nav').innerHTML=Object.entries(pages).map(([id,[name]])=>`<a href="#${id}" class="${page===id?'active':''}" ${page===id?'aria-current="page"':''}>${name}</a>`).join('');$('#pageTitle').textContent=pages[page][0];$('#subtitle').textContent=pages[page][1];notice('');({dashboard,files,wifi,settings,ai,ota,account}[page])();enhanceControls();}
window.addEventListener('hashchange',render);
const metric=(value,sub)=>`<div class="metric">${escape(value)}</div><small>${escape(sub)}</small>`;
function widgetValue(id){return widgetContent(id,status);}
function dashboard(){$('#content').innerHTML=`<div class="toolbar"><div><h2>วันนี้ พอดีกับคุณ</h2><p class="hint">ลากมุมล่างเพื่อปรับขนาด · ใช้ลูกศรเพื่อย้ายบล็อก</p></div><div class="row"><select id="addType" aria-label="ชนิดบล็อก">${Object.entries(widgets).map(([id,name])=>`<option value="${id}">${name}</option>`).join('')}</select><button id="addBlock" class="primary">+ เพิ่มบล็อก</button><button id="resetLayout">เริ่มใหม่</button></div></div><div class="grid" id="dashboard"></div>`;drawBlocks();$('#addBlock').onclick=()=>{const id=$('#addType').value;if(!blocks.some(b=>b.id===id)){blocks.push({id,w:6,h:220});saveLayout();drawBlocks();}else notice('มีบล็อกนี้อยู่แล้ว');};$('#resetLayout').onclick=()=>{blocks=defaults();saveLayout();drawBlocks();};}
function drawBlocks(){stopCardObserver?.();$('#dashboard').innerHTML=blocks.map((b,i)=>`<section class="widget" data-id="${b.id}" style="--span:${b.w};--height:${b.h}px;--rows:${(b.h+20)/80}"><div class="widget-head"><h3>${widgets[b.id]}</h3><div class="widget-actions"><button data-action="up" aria-label="ย้าย ${widgets[b.id]} ขึ้น" ${i===0?'disabled':''}>↑</button><button data-action="down" aria-label="ย้าย ${widgets[b.id]} ลง" ${i===blocks.length-1?'disabled':''}>↓</button><button data-action="remove" aria-label="ลบ ${widgets[b.id]}">×</button></div></div><div data-value="${b.id}">${widgetValue(b.id)}</div><span class="block-size">${b.w}/12 | ${b.h} px</span><button class="resize" aria-label="ปรับขนาด ${widgets[b.id]} ใช้ปุ่มลูกศร"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 3H3v5m13 13h5v-5M3 3l6 6m12 12-6-6"/></svg></button></section>`).join('')||'<p class="empty">เพิ่มบล็อกแรกเพื่อเริ่มจัดพื้นที่ของคุณ</p>';
 $$('.widget').forEach(el=>{const id=el.dataset.id,b=blocks.find(b=>b.id===id);$$('[data-action]',el).forEach(btn=>btn.onclick=()=>{const i=blocks.indexOf(b),a=btn.dataset.action;if(a==='remove')blocks.splice(i,1);else{const j=i+(a==='up'?-1:1);[blocks[i],blocks[j]]=[blocks[j],blocks[i]];}saveLayout();drawBlocks();});const handle=$('.resize',el);handle.onpointerdown=e=>{handle.setPointerCapture(e.pointerId);const x=e.clientX,y=e.clientY,w=b.w,h=b.h,unit=($('#dashboard').clientWidth+20)/12;$('#dashboard').classList.add('snapping');handle.onpointermove=e=>{b.w=snapWidth(w+(e.clientX-x)/unit);b.h=snapHeight(h+e.clientY-y);sizeCard(el,b);};handle.onpointerup=handle.onpointercancel=handle.onlostpointercapture=()=>{handle.onpointermove=null;$('#dashboard')?.classList.remove('snapping');saveLayout();};};handle.onkeydown=e=>{if(!e.key.startsWith('Arrow'))return;e.preventDefault();b.w=snapWidth(b.w+(e.key==='ArrowRight'?3:e.key==='ArrowLeft'?-3:0));b.h=snapHeight(b.h+(e.key==='ArrowDown'?80:e.key==='ArrowUp'?-80:0));sizeCard(el,b);saveLayout();};});stopCardObserver=observeCards($('#dashboard'),blocks,saveLayout);}
const toggle=(key,title,on)=>`<label class="switch">${title}<input type="checkbox" name="${key}" ${on?'checked':''} role="switch"></label>`;
async function saveSettings(values){await api('settings',{values:JSON.stringify(values)});notice('ส่งการตั้งค่าแล้ว รอผลการบันทึกจากอุปกรณ์');}
function wifi(){$('#content').innerHTML=`<div class="two"><form class="panel" id="wifiForm"><span class="badge">NETWORK</span><h2>เชื่อมต่อ WiFi</h2><p>บันทึกเครือข่ายสำหรับการเปิดเครื่องครั้งถัดไป</p><label>ชื่อเครือข่าย (SSID)<input name="ssid" value="${escape(status.ssid)}" maxlength="32" required autocomplete="off"></label><label>รหัสผ่าน<input name="password" type="password" maxlength="63" autocomplete="new-password" placeholder="เว้นว่างสำหรับเครือข่ายเปิด"></label><button class="primary">บันทึกและเชื่อมต่อ</button><p class="hint">เครือข่าย 2.4 GHz · หน้าเว็บยังเปิดผ่าน AP ของ ToFan ได้</p></form><section class="panel"><h2>สถานะเครือข่าย</h2><div id="wifiStatus"></div>${toggle('wifi','เชื่อมต่อ WiFi อัตโนมัติ',status.settings?.wifi)}<p class="hint">เปิดเว็บจัดการได้จาก Admin mode บนตัวเครื่อง</p></section></div>`;$('#wifiForm').onsubmit=attempt(async e=>{await api('wifi',Object.fromEntries(new FormData(e.target)));notice('บันทึกและกำลังเชื่อมต่อ กรุณารอสถานะจากเครื่อง');});$('[name=wifi]').onchange=attempt(e=>saveSettings({wifi:+e.target.checked}));updateWifi();}
function updateWifi(){if(!$('#wifiStatus'))return;$('#wifiStatus').innerHTML=metric(status.networkBusy?'กำลังเชื่อมต่อ…':status.connected?'เชื่อมต่อแล้ว':'Access Point',status.connected?`${status.ssid} · ${status.ip} · ${status.rssi} dBm`:`เปิดเว็บที่ ${status.apIP||'192.168.4.1'}`);}
function settings(){const s=status.settings||{};$('#content').innerHTML=`<div class="two"><form id="soundSettings" class="panel"><h2>เสียงและการเล่นเพลง</h2><label>ระดับเสียง <output id="volumeValue">${s.volume??50}%</output><input name="volume" type="range" min="0" max="100" value="${s.volume??50}"></label><label>ระดับต่อหนึ่งกึกของตัวหมุน<select name="volumeStep">${[2,3,4,5].map(n=>`<option ${s.volumeStep===n?'selected':''}>${n}</option>`).join('')}</select></label>${toggle('autoNext','เล่นเพลงถัดไปอัตโนมัติ',s.autoNext)}${toggle('shuffle','สุ่มเพลง',s.shuffle)}${toggle('voice','Voice assistant · เปิด inference',s.voice)}<button class="primary">บันทึกการตั้งค่า</button></form><section class="panel"><h2>Display settings</h2><p>เลือกส่วนที่ต้องการ แล้วแตะวงล้อสี</p><label>ส่วนของหน้าจอ<select id="colorRole">${['พื้นหลัง','พื้นผิว','ข้อความ','สีหลัก','ข้อความรอง','รายการที่เลือก'].map((n,i)=>`<option value="${i}">${n}</option>`).join('')}</select></label><div class="row"><canvas id="wheel" class="color-wheel" width="150" height="150" aria-label="วงล้อสี"></canvas><input id="colorHex" type="color" aria-label="เลือกสีแบบตัวเลข" style="width:70px"></div><label>ความสว่าง<input id="brightness" type="range" min="0" max="100"></label><div id="colorPreview" class="panel">ตัวอย่างสีที่เลือก</div><button id="saveColors" class="primary">บันทึกสีหน้าจอ</button><p class="hint">สีและการตั้งค่าจดจำในเครื่อง แม้ปิดเครื่องแล้วเปิดใหม่</p></section></div>`;
 $('[name=volume]').oninput=e=>$('#volumeValue').textContent=e.target.value+'%';$('#soundSettings').onsubmit=attempt(e=>saveSettings({volume:+$('[name=volume]').value,volumeStep:+$('[name=volumeStep]').value,...Object.fromEntries(['autoNext','shuffle','voice'].map(k=>[k,+$(`[name=${k}]`).checked]))}));
 const colors=structuredClone(s.colors||[[160,3,98],[155,9,94],[205,30,22],[160,30,79],[205,17,49],[165,19,88]]),canvas=$('#wheel'),ctx=canvas.getContext('2d'),img=ctx.createImageData(150,150);
 function rgb([h,s,v]){s/=100;v/=100;const f=n=>{const k=(n+h/60)%6;return Math.round(255*(v-v*s*Math.max(0,Math.min(k,4-k,1))));};return[f(5),f(3),f(1)];}
 for(let y=0;y<150;y++)for(let x=0;x<150;x++){const dx=x-75,dy=y-75,r=Math.hypot(dx,dy),i=(y*150+x)*4;if(r<=75){img.data.set([...rgb([(Math.atan2(dy,dx)*180/Math.PI+360)%360,r/75*100,100]),255],i);}}ctx.putImageData(img,0,0);
 const show=()=>{const c=colors[+$('#colorRole').value],hex='#'+rgb(c).map(n=>n.toString(16).padStart(2,'0')).join('');$('#brightness').value=c[2];$('#colorHex').value=hex;$('#colorPreview').style.background=hex;$('#colorPreview').style.color=c[2]>60?'#243b31':'white';};
 const choose=e=>{const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*150-75,y=(e.clientY-r.top)/r.height*150-75,c=colors[+$('#colorRole').value];c[0]=Math.round((Math.atan2(y,x)*180/Math.PI+360)%360)%360;c[1]=Math.round(Math.min(100,Math.hypot(x,y)/75*100));show();};canvas.onpointerdown=e=>{canvas.setPointerCapture(e.pointerId);choose(e);canvas.onpointermove=choose;};canvas.onpointerup=()=>canvas.onpointermove=null;
 $('#colorRole').onchange=show;$('#brightness').oninput=e=>{colors[+$('#colorRole').value][2]=+e.target.value;show();};$('#colorHex').oninput=e=>{const a=e.target.value.match(/\w\w/g).map(x=>parseInt(x,16)/255),max=Math.max(...a),min=Math.min(...a),d=max-min;let h=0;if(d)h=max===a[0]?((a[1]-a[2])/d+6)%6:max===a[1]?(a[2]-a[0])/d+2:(a[0]-a[1])/d+4;colors[+$('#colorRole').value]=[Math.round(h*60)%360,Math.round(max?d/max*100:0),Math.round(max*100)];show();};$('#saveColors').onclick=attempt(()=>saveSettings({colors}));show();}
function ai(){
 const a=status.ai||{},live=(a.provider||'gemini-live')==='gemini-live';
 $('#content').innerHTML=`<form id="aiForm" class="panel"><h2>บริการสนทนา</h2>
 ${toggle('enabled','เปิด AI conversation',a.enabled)}
 <label>Provider<select name="provider" id="aiProvider"><option value="gemini-live" ${live?'selected':''}>Gemini Live (ไมค์ → เสียงตอบกลับ)</option><option value="backend" ${!live?'selected':''}>HTTP backend เดิม</option></select></label>
 <label>API key<input name="apiKey" type="password" maxlength="159" placeholder="${a.apiKeySet?'ตั้งค่าแล้ว · เว้นว่างเพื่อคงค่าเดิม':'ใส่ API key'}"></label>
 <div id="geminiLiveFields">
   <div class="two"><label>Gemini Live model<input name="model" value="${escape(a.model||'gemini-3.1-flash-live-preview')}" maxlength="63" placeholder="gemini-3.1-flash-live-preview"></label><label>Voice<input name="voice" value="${escape(a.voice||'Kore')}" maxlength="31" placeholder="Kore"></label></div>
   <label>System instruction<textarea name="systemInstruction" maxlength="511" rows="5" placeholder="บุคลิกและวิธีตอบของ AI Pet">${escape(a.systemInstruction||'You are ToFan, a friendly desk companion. Respond naturally and briefly. If the user speaks Thai, reply in Thai.')}</textarea></label>
   ${toggle('liveBargeIn','อนุญาตให้พูดแทรกขณะ Gemini กำลังตอบ',a.liveBargeIn)}
   <p class="hint">เมื่ออยู่หน้า AI Pet จะเชื่อม Gemini Live แบบเสียงเท่านั้น: ไมค์ 16 kHz → Gemini และเสียงตอบกลับ 24 kHz → ลำโพงของ ToFan โดยตรง</p>
 </div>
 <div id="legacyAiFields">
   <label>Pipeline URL<input name="pipelineUrl" type="url" value="${escape(a.pipelineUrl||'')}" maxlength="191" placeholder="https://.../voice"></label>
   <div class="two"><label>ชื่อผู้ใช้บริการ<input name="user" maxlength="63" placeholder="เว้นว่างเพื่อคงค่าเดิม"></label><label>รหัสผ่านบริการ<input name="password" type="password" maxlength="63" placeholder="เว้นว่างเพื่อคงค่าเดิม"></label></div>
 </div>
 ${toggle('allowInsecureTLS','อนุญาต TLS ที่ไม่ตรวจใบรับรอง (ใช้เฉพาะระบบทดสอบ)',a.allowInsecureTLS)}
 <p class="hint" id="aiState">สถานะ: ${escape(a.state||'idle')}${a.lastError?` · ${escape(a.lastError)}`:''}</p>
 <button class="primary">บันทึก</button></form>`;
 const switchMode=()=>{const isLive=$('#aiProvider').value==='gemini-live';$('#geminiLiveFields').hidden=!isLive;$('#legacyAiFields').hidden=isLive;};
 $('#aiProvider').onchange=switchMode;switchMode();
 $('#aiForm').onsubmit=attempt(async e=>{
   const values=Object.fromEntries(new FormData(e.target));
   for(const k of ['apiKey','user','password'])if(!values[k])delete values[k];
   for(const k of ['enabled','allowInsecureTLS','liveBargeIn'])values[k]=$(`[name=${k}]`).checked;
   if(values.provider==='gemini-live'){
     delete values.pipelineUrl;delete values.user;delete values.password;
   }else{
     delete values.voice;delete values.systemInstruction;delete values.liveBargeIn;
   }
   await api('ai',{values:JSON.stringify(values)});notice('ส่งการตั้งค่า AI แล้ว');
 });
}
function ota(){$('#content').innerHTML=`<section class="panel"><span class="badge">FIRMWARE</span><h2>พร้อมสำหรับสิ่งใหม่</h2><p>รุ่นปัจจุบัน ${escape(status.firmware||'—')}</p><p class="hint">ไฟล์ application firmware.bin สำหรับ ESP32-S3 · ไม่ใช่ไฟล์ merged flash หรือ bootloader · สูงสุด ${bytes(status.slotSize)}</p><p class="warning">หยุดเพลงและการอัดเสียงก่อนอัปเดต รักษาไฟเลี้ยงจนเครื่องเริ่มใหม่ ข้อมูลบน SD และการตั้งค่าจะไม่ถูกฟอร์แมต</p><div class="two"><form id="otaFile"><h3>จากไฟล์ในเครื่อง</h3><label>ไฟล์เฟิร์มแวร์<input name="file" type="file" accept=".bin" required></label><button class="primary">ตรวจสอบและอัปเดต</button></form><form id="otaUrl"><h3>จากลิงก์</h3><label>ลิงก์ไฟล์ .bin<input name="url" type="url" required placeholder="https://your-server/firmware.bin" maxlength="1023"></label><p class="hint">ลิงก์ดาวน์โหลดตรงพร้อม Content-Length ไม่มี redirect · HTTPS ตรวจใบรับรอง · HTTP ไม่มีการเข้ารหัส</p><button>ดาวน์โหลดและอัปเดต</button></form></div><progress id="transferProgress" max="100" value="0"></progress><button id="cancelUpload" hidden>ยกเลิกการส่งไฟล์</button><p id="otaState" role="status">ยังไม่มีการอัปเดต</p></section>`;$('#otaFile').onsubmit=attempt(async e=>{const file=e.target.file.files[0];if(file.size>status.slotSize||file.size<24)throw Error('ขนาดเฟิร์มแวร์ไม่ถูกต้อง');const h=new Uint8Array(await file.slice(0,24).arrayBuffer());if(h[0]!==233||h[12]!==9||h[13]!==0)throw Error('ไม่ใช่ application image ของ ESP32-S3');if(!await ask(`อัปเดต ToFan ด้วย ${file.name} (${bytes(file.size)})? เครื่องจะเริ่มใหม่เมื่อสำเร็จ`))return;await upload('ota/file',file,file.name);notice('ตรวจสอบเฟิร์มแวร์สำเร็จ เครื่องกำลังเริ่มใหม่');});$('#otaUrl').onsubmit=attempt(async e=>{const url=e.target.url.value;if(!await ask(`ดาวน์โหลดและติดตั้งเฟิร์มแวร์จาก\n${url}\nเครื่องจะเริ่มใหม่เมื่อสำเร็จ`))return;await api('ota/url',{url});notice('อุปกรณ์เริ่มดาวน์โหลดเฟิร์มแวร์แล้ว');});}
setInterval(async()=>{if(!token||polling)return;polling=true;try{const prev=status.settingsRevision;status=await api('status');recordStatus(status);loadLayout();applyWebTheme();$('#connection').textContent=status.connected?'● เชื่อมต่อแล้ว':'● Access Point';if(status.settingsResult&&prev!==status.settingsRevision)notice(status.settingsResult,/failed|Invalid|Cannot|busy|Exit AI Pet/i.test(status.settingsResult));if(page==='dashboard')$$('[data-value]').forEach(el=>el.innerHTML=widgetValue(el.dataset.value));if(page==='wifi')updateWifi();if(page==='files')updateAudioImportStatus();if(page==='ai'&&$('#aiState'))$('#aiState').textContent=`สถานะ: ${status.ai?.state||'idle'}${status.ai?.lastError?' · '+status.ai.lastError:''}`;if(page==='ota'){const ota=await api('ota');if($('#otaState')){$('#otaState').textContent=ota.error||({idle:'พร้อมอัปเดต',connecting:'กำลังเชื่อมต่อ',uploading:'กำลังรับไฟล์',downloading:'กำลังดาวน์โหลด',rebooting:'อัปเดตสำเร็จ กำลังเริ่มใหม่',error:'อัปเดตไม่สำเร็จ'}[ota.state]||ota.state);if(ota.total&&!xhr)$('#transferProgress').value=ota.done/ota.total*100;}}}catch(e){$('#connection').textContent='○ ขาดการเชื่อมต่อ';}finally{polling=false;}},2000);
boot().catch(e=>notice(e.message,true));

document.body.append($('#notice'));

mobileMenu();

startIcons();
