const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function validMac(s){return /^(?:[0-9a-f]{2}:){5}[0-9a-f]{2}$/i.test(s)&&!(parseInt(s.slice(0,2),16)&1)&&!/^00(?::00){5}$/.test(s);}
export function mountEspNow({root,api,ask,notice}){
 let state=null,dirty=false,pending=false,polling=false;
 root.innerHTML=`<section class="panel"><span class="badge">ESP-NOW</span><h2>เชื่อมต่ออุปกรณ์ slave</h2><p id="nowStatus" role="status">กำลังโหลด…</p><p class="hint">ใช้ช่องเดียวกับ Wi-Fi ปัจจุบัน ต้องตั้ง slave ให้ตรงกัน · แพ็กเก็ตไม่เข้ารหัส · ออนไลน์เมื่อได้รับคำตอบภายใน 15 วินาที</p><p>MAC ตัวเครื่อง (STA): <code id="nowMac">…</code></p><label class="switch">เปิด ESP-NOW<input id="nowEnabled" type="checkbox" role="switch"></label><p class="hint">การเปิด ESP-NOW จะเปิดวิทยุ Wi-Fi แม้ไม่ได้เชื่อมต่อเราเตอร์</p><div id="nowPeers"></div><div class="row"><button id="nowAdd" type="button"><i class="fa-solid fa-plus"></i> เพิ่ม slave</button><button id="nowSave" class="primary" type="button">บันทึกการเชื่อมต่อ</button></div><p id="nowError" role="status"></p></section><section class="panel"><h2>ส่งแพ็กเก็ตทดสอบ</h2><form id="nowSend"><label>อุปกรณ์ปลายทาง<select name="mac" required></select></label><label>ข้อมูล hexadecimal (สูงสุด 200 ไบต์)<textarea name="hex" maxlength="400" placeholder="48656C6C6F"></textarea></label><button class="primary">ส่งข้อมูล</button></form><p class="hint">TX คือผลส่งระดับวิทยุ ส่วน RX คือแพ็กเก็ตตอบกลับจริง · ข้อมูลรับล่าสุดแสดงเป็น hexadecimal</p><div id="nowTelemetry"></div></section>`;
 const $=s=>root.querySelector(s);
 function rows(){return [...root.querySelectorAll('.now-peer')].map(row=>({name:row.querySelector('[name=name]').value.trim(),mac:row.querySelector('[name=mac]').value.trim().toUpperCase(),enabled:row.querySelector('[name=enabled]').checked}));}
 function draw(peers){$('#nowPeers').innerHTML=peers.map(p=>`<div class="now-peer panel"><label>ชื่อ slave<input name="name" value="${escape(p.name)}" maxlength="24"></label><label>MAC address<input name="mac" value="${escape(p.mac)}" maxlength="17" placeholder="AA:BB:CC:DD:EE:FF"></label><label class="switch">เปิดใช้อุปกรณ์<input name="enabled" type="checkbox" role="switch" ${p.enabled?'checked':''}></label><button type="button" data-remove>ลบ slave</button></div>`).join('');root.querySelectorAll('[data-remove]').forEach(button=>button.onclick=async()=>{if(await ask('ลบ slave นี้จากรายการ? กดบันทึกเพื่อยืนยันการเปลี่ยนแปลง')){button.closest('.now-peer').remove();dirty=true;}});}
 function show(s){state=s;$('#nowMac').textContent=s.mac||'ไม่พร้อม';$('#nowStatus').textContent=`${s.ready?'พร้อมรับส่ง':s.enabled?'กำลังเริ่ม':'ปิดอยู่'} · ช่อง ${s.channel||'-'} · ${(s.peers||[]).filter(p=>p.online).length}/${(s.peers||[]).length} ออนไลน์`;$('#nowError').textContent=s.error||'';
  if(!dirty){$('#nowEnabled').checked=!!s.enabled;draw(s.peers||[]);}
  const select=$('#nowSend [name=mac]'),selected=select.value;select.innerHTML=(s.peers||[]).filter(p=>p.enabled&&p.registered).map(p=>`<option value="${escape(p.mac)}">${escape(p.name)}</option>`).join('');if([...select.options].some(o=>o.value===selected))select.value=selected;select.dispatchEvent(new Event("change"));
  $('#nowTelemetry').innerHTML=(s.peers||[]).map(p=>`<article class="panel"><strong>${escape(p.name)}</strong><p>${!p.enabled?'ปิดใช้งาน':p.online?'ออนไลน์':p.seen?'ไม่ได้รับคำตอบล่าสุด':'ยังไม่ได้รับคำตอบ'} · TX ${Number(p.tx)||0} / RX ${Number(p.rx)||0} / ส่งไม่สำเร็จ ${Number(p.failed)||0}</p><p class="hint">รับล่าสุด: <code style="overflow-wrap:anywhere">${escape(p.payloadHex||'—')}</code></p></article>`).join('');
 }
 async function refresh(){if(polling||!root.isConnected||pending)return;polling=true;try{show(await api('espnow'));}catch(e){$('#nowError').textContent=e.message;}finally{polling=false;}}
 root.addEventListener('focusin',e=>{if(e.target.closest('#nowPeers'))dirty=true;});
 root.addEventListener('input',e=>{if(e.target.closest('#nowPeers')||e.target.id==='nowEnabled')dirty=true;});
 $('#nowAdd').onclick=()=>{const peers=rows();if(peers.length>=8){notice('เพิ่มได้สูงสุด 8 อุปกรณ์',true);return;}peers.push({name:'Slave '+(peers.length+1),mac:'',enabled:true});dirty=true;draw(peers);};
 async function waitResult(revision){for(let i=0;i<40;++i){await new Promise(r=>setTimeout(r,250));const s=await api('espnow');if(s.revision!==revision){if(s.error)throw Error(s.error);return s;}}throw Error('ยังรอผลจากเครื่อง กรุณารีเฟรชสถานะก่อนลองใหม่');}
 $('#nowSave').onclick=async()=>{if(pending||!state)return;const peers=rows();try{const seen=new Set();for(const p of peers){if(!p.name||new TextEncoder().encode(p.name).length>24||!validMac(p.mac)||p.mac===state.mac||seen.has(p.mac))throw Error('ตรวจชื่อ (ไม่เกิน 24 ไบต์) และ MAC: ห้ามซ้ำหรือใช้ MAC ตัวเครื่อง');seen.add(p.mac);}pending=true;$('#nowSave').disabled=true;const rev=state.revision;await api('espnow',{values:JSON.stringify({enabled:$('#nowEnabled').checked,peers})});const next=await waitResult(rev);dirty=false;show(next);notice('บันทึก ESP-NOW แล้ว');}catch(e){notice(e.message,true);}finally{pending=false;$('#nowSave').disabled=false;}};
 $('#nowSend').onsubmit=async e=>{e.preventDefault();if(pending||!state)return;try{const f=new FormData(e.target),hex=String(f.get('hex')).replace(/\s/g,'');if(!f.get('mac')||!/^(?:[0-9a-f]{2}){0,200}$/i.test(hex))throw Error('เลือก slave และใส่ hexadecimal เป็นคู่ สูงสุด 200 ไบต์');pending=true;const rev=state.revision;await api('espnow/send',{mac:f.get('mac'),hex});show(await waitResult(rev));notice('ส่งเข้าระบบแล้ว ตรวจผล TX และคำตอบ RX');}catch(e){notice(e.message,true);}finally{pending=false;}};
 refresh();const timer=setInterval(()=>{if(!root.isConnected){clearInterval(timer);return;}refresh();},2000);
}
